### ISSUE TITLE
Globals in Types not intialized when type.new() is called

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#447] opened 2019-05-16 22:48 UTC
Phew ... took a while to narrow it down - but I have issues creating a small example (as it works there).

So in essence I do this (but as said the following _works_ it is just there to sketch out the basic layout):
```blitzmax
SuperStrict
Framework Brl.StandardIO

Type TMyType
	Function Create:TMyType()
	End Function
End Type


Type TTestBase
	Global my1:TMyType = TMyType.Create()
End Type


Type TTest Extends TTestBase
	Field other:TOther

	Method New()
		other = New TOther
		'passing an global
		other.Init(my1)
	End Method

End Type


Type TOther
	Method Init(mytype:TMyType)
		If mytype Then Print "mytype was passed"
		If mytype Then Print mytype.ToString() '<---- here it sigsevs in the real code
	End Method
End Type


Local t:TTest = New TTest
```

So I have types which pass a global as param to other functions.
The interesting part is, that it is of the opinion to have received a valid object ("mytype was passed" is printed). But as soon as I want to access a property/method of this object I receive the segfault.

this then looks like this:
```gdb
Thread 1 "test.visual.off" received signal SIGSEGV, Segmentation fault.
0x0000000000841054 in __m_game_screen_statistics_TDataChart_RenderDataSet_iiiTTColor (o=0x7fffeec25b60, bbt_dsIndex=0, bbt_xOffset=0, bbt_yOffset=0, 
    bbt_colorOverride=0x139a680 <bbNullObject>)
    at /project/source/.bmx/game.screen.statistics.bmx.debug.linux.x64.c:9773
9773			(((struct _m_base_util_color_TColor_obj*)bbNullObjectTest((bbt_3 = ((struct _m_base_util_color_TColor_obj**)BBARRAYDATAINDEX((((struct _m_game_screen_statistics_TDataChart_obj*)bbNullObjectTest(o))->__m_game_screen_statistics_tdatachart_datasetcolors ),(((struct _m_game_screen_statistics_TDataChart_obj*)bbNullObjectTest(o))->__m_game_screen_statistics_tdatachart_datasetcolors )->dims,((BBUINT)bbt_dsIndex)))[((BBUINT)bbt_dsIndex)])))->clas)->m_setRGBA((struct _m_base_util_color_TColor_obj*)bbt_3);
(gdb) bt
#0  0x0000000000841054 in __m_game_screen_statistics_TDataChart_RenderDataSet_iiiTTColor (o=0x7fffeec25b60, bbt_dsIndex=0, bbt_xOffset=0, bbt_yOffset=0, 
    bbt_colorOverride=0x139a680 <bbNullObject>)
    at /project/source/.bmx/game.screen.statistics.bmx.debug.linux.x64.c:9773
```

Corresponding C code was this:
```C
		bbOnDebugEnterScope(&__scope);
		struct BBDebugStm __stmt_0 = {"/project/source/game.screen.statistics.bmx", 1958, 0};
		bbOnDebugEnterStm(&__stmt_0);
		struct _m_base_util_color_TColor_obj* bbt_3;
		(((struct _m_base_util_color_TColor_obj*)bbNullObjectTest((bbt_3 = ((struct _m_base_util_color_TColor_obj**)BBARRAYDATAINDEX((((struct _m_game_screen_statistics_TDataChart_obj*)bbNullObjectTest(o))->__m_game_screen_statistics_tdatachart_datasetcolors ),(((struct _m_game_screen_statistics_TDataChart_obj*)bbNullObjectTest(o))->__m_game_screen_statistics_tdatachart_datasetcolors )->dims,((BBUINT)bbt_dsIndex)))[((BBUINT)bbt_dsIndex)])))->clas)->m_setRGBA((struct _m_base_util_color_TColor_obj*)bbt_3);
		bbOnDebugLeaveScope();
```
(Line 9773 is the 5th in the code above). It was about calling a method if the variable/reference to the type is valid.

**Comment by GWRon** [comment] 2019-05-17 07:41
In my case the difference is:
- the type which is referenced in the global is defined in an imported file (`TColor`)
- the base and extended types passing this global in functions called in their `New()` are stored in another import
- main file imports the "base/extended types" file

Interestingly it is working for a type but not for another one (which does some more array-stuff in which these types are stored too).

**Comment by GWRon** [comment] 2019-05-17 15:17
Seems the global initialization is not done _before_ intializing an instance via `new()`.

```BlitzMax
Type TMyColor extends TColor
	Function Create:TColor(r:int=0,g:int=0,b:int=0,a:float=1.0)
		print "creating color"
		return Super.Create(r,g,b,a)
	End Function
End Type



Type TStatisticsSubScreen
	Field LS_screenName:TLowerString

	Global programmeColor:TColor = TMyColor.Create(110,180,100)
	Global newsColor:TColor = TMyColor.Create(110,100,180)
[...]
End Type



Type TStatisticsSubScreen_Audience extends TStatisticsSubScreen
[..]
	Method New()
[..]
print "TStatisticsSubScreen_Audience.New()"
[..]
print "adding newscolor"
		dataChart.AddDataSet(new TDataChartDataSet, newsColor, new TVec2D.Init(3,0))
[..]
	End Method
```
the line "creating color" is not printed before the segfault. But it would be printed if I re-initialized them at the top of the `Method New()`:

```BlitzMax
	Method New()
		programmeColor:TColor = TMyColor.Create(110,180,100)
[..]
	End Method
```
It then compiles, runs - and prints out "creating color".

As said the most interesting part is, that the logic says `true` to `if programmeColor then ...` - while it seems to be in a limbo state or so.

**Comment by woollybah** [comment] 2019-05-17 16:24
If `programmeColor` hasn't even been initialised yet, then it would be a pointer to 0. BlitzMax tests for Null against a specific null object instance, and therefore the test would return true. (`if not nullInstance`)

**Comment by GWRon** [comment] 2019-05-17 16:29
So I could check with `if TColor(programmeColor) then...` ?
Would read a bit odd... For programmeColor being defined as `TColor` already.

Regardless of this it is a bug (in my opinion) that a global of a type is not set to its defined value when a new instance of the object is to get created.

I thought globals are created on programme start ...not on type usage.

Might be related to the global-local-issue I created some days ago.

**Comment by GWRon** [comment] 2019-05-17 16:36
Also: if I removed the ToString() part I get the crash elsewhere... So I think it passes this nullPointer thing as param...which gets stored in the other references. Then the global is defined and so `programmeColor` becomes valid while its referenced contain the borked reference (nullPointer).

As this already passed `bcc` this won't be catched there.


Does that make sense or did I misunderstand what you were trying to explain to me?

**Comment by HurryStarfish** [comment] 2019-05-17 17:48
> I thought globals are created on programme start ...not on type usage.

Yeah, that's how it should be, and that's how it worked in vanilla.
Globals _inside a type_ (!) are supposed to be initialized immediately when the module/file is imported (before any top-level/"main" code runs). Twice, actually. First, all of them should get initialized to their default values. Then, in a second pass, with their actual initializers, in the order they appear in the code. This is important if the initializers refer to other globals:

```BlitzMax
SuperStrict
Framework BRL.StandardIO

Print T1.G
Print T2.G
Global GTopLvl:String = InitTopLvl()

Type T1
	Global G:String = T1.Init()
	Function Init:String()
		Print "T1.Init"
		Return T2.G
	End Function
End Type

Type T2
	Global G:String = T2.Init()
	Function Init:String()
		Print "T2.Init"
		Return "hello"
	End Function
End Type

Function InitTopLvl:String()
	Print "InitTopLvl"
	Return "asdf"
End Function
```
If this code is run in vanilla, it prints
```
T1.Init
T2.Init

hello
InitTopLvl
```
Because what happens is the following, in this order:
1. `T1.G` and `T2.G` get "pre-initialized" to the default value of `String`, which is `""` 
2. the initializer of `T1.G` runs (`T1.Init()`), prints "T1.Init" and returns `T2.G`, which is `""` at this time
   - as a result, `""` is assigned to `T1.G`
3. the initializer of `T2.G` runs (`T2.Init()`), prints "T2.Init" and returns `"hello"`
   - as a result, `"hello"` is assigned to `T2.G`
4. the main code of the file is run
   - `Print T1.G` prints ""
   - `Print T2.G` prints "hello"
   - because `GTopLvl` is a Global at top-level and not in a type, it is initialized only now, once program execution has reached its declaration; its the initializer (`InitTopLvl()`) runs now and prints "InitTopLvl"

Any `Framework`/`Import`s are initialized in the same way, but `before` all this. So basically there is also a step 0., which is "do step 1.-4. for any imported modules/files first" (and this one will do _its_ imports first etc.).

**Comment by GWRon** [comment] 2019-05-17 18:03
Glad you got a ~running~ crashing example ready for Brucey to cudgel his brain ;-)

Maybe #440 is suitable to get tackled in the same patch.

**Comment by HurryStarfish** [comment] 2019-05-17 18:10
It gets a bit more complicated when you throw top-level and Function-level Globals into the mix.

Top-level globals, as I said in the previous post, are initialized once control flow reaches their declaration. They are not allowed to be accessed by other top-level code "before" then (which NG currently also gets "wrong"):
```BlitzMax
Print GGG ' <- error in vanilla, should be the same in NG
Global GGG:String = "hi"
```
*But* initializers of Type-level-Globals can observe them in their "pre-initialized" (default value) state:
```BlitzMax
SuperStrict
Framework BRL.StandardIO

Print "main"

Global GGG:String = InitGGG()
Print T1.G

Print "main end"

Type T1
	Global G:String = T1.Init()
	Function Init:String()
		Print "T1.Init"
		Return GGG
	End Function
End Type

Function InitGGG:String()
	Print "InitGGG"
	Return "asdf"
End Function
```
This prints
```
T1.Init
main
InitGGG

main end
```
The empty line comes from `Print T1.G`, because `T1.Init` was reading `GGG` before `InitGGG` ran.


I will open an extra issue for Globals inside Functions later, since there is an additional point I'd like to discuss about those.

**Comment by HurryStarfish** [comment] 2019-05-17 18:22
> Glad you got a running crashing example ready for Brucey to cudgel his brain ;-)
> Thanks for your example.

I experimented with this stuff to find out how it behaves back when I wrote my BlitzMax pre-compiler. Caused me some heachaches back then too. :slightly_smiling_face: 

> Maybe #440 is suitable to get tackled in the same patch.

We have the older issue #252 on this topic, too.

**Comment by GWRon** [comment] 2019-05-17 18:24
Yes ... all collected in one place now ... the best bouquet of ~flowers~ bugs we could bundle for our beloved @woollybah  :-)

**Closed** 2019-05-27 21:12 UTC

**Comment by GWRon** [comment] 2019-06-15 11:38
Somehow this still does not work for me (updated bcc, bmk, brl, pub, recompiled everything).

```BlitzMax
Type TScreenHandler_OfficeStatistics Extends TScreenHandler
	Global programmeColor:TColor = TColor.Create(110,180,100)
	Global newsColor:TColor = TColor.Create(110,100,180)
End Type


Type TStatisticsSubScreen
End Type


Type TStatisticsSubScreen_Audience extends TStatisticsSubScreen
	Method New()
		if not TScreenHandler_OfficeStatistics.newsColor then throw "oops"
	End Method
End Type
```

Always `oops` is thrown.

**Comment by GWRon** [comment] 2019-06-15 11:53
So I replaced the color creation similar to above:

```BlitzMax
Type TMyColor extends TColor
	Function Create:TColor(r:int=0,g:int=0,b:int=0,a:float=1.0)
		print "creating color"
		return Super.Create(r,g,b,a)
	End Function
End Type


Type TScreenHandler_OfficeStatistics Extends TScreenHandler
	Global programmeColor:TColor = TColor.Create(110,180,100)
	Global newsColor:TColor = TColor.Create(110,100,180)
End Type


Type TStatisticsSubScreen
End Type


Type TStatisticsSubScreen_Audience extends TStatisticsSubScreen
	Method test(color:TColor)
	End Method

	Method New()
		print "new TStatisticsSubScreen_Audience"
		'pass the global als a param
		test( TScreenHandler_OfficeStatistics.newsColor )
print "done"

	End Method
End Type
```

output is:
```
new TStatisticsSubScreen_Audience
done
creating color
creating color
```
so the globals are created AFTER the instance of a type is created.

**Comment by woollybah** [comment] 2019-06-15 13:15
```blitzmax
SuperStrict

Framework brl.standardio

New TStatisticsSubScreen_Audience

Type TColor
	Function Create:TColor(r:Int, g:Int, b:Int, a:Float)
	End Function
End Type

Type TScreenHandler
End Type 

Type TMyColor Extends TColor
	Function Create:TColor(r:Int=0,g:Int=0,b:Int=0,a:Float=1.0)
		Print "creating color"
		Return Super.Create(r,g,b,a)
	End Function
End Type


Type TScreenHandler_OfficeStatistics Extends TScreenHandler
	'use the TMyColor create function !
	Global programmeColor:TColor = TMyColor.Create(110,180,100)
	Global newsColor:TColor = TMyColor.Create(110,100,180)
End Type


Type TStatisticsSubScreen
End Type


Type TStatisticsSubScreen_Audience Extends TStatisticsSubScreen
	Method test(color:TColor)
	End Method

	Method New()
		Print "new TStatisticsSubScreen_Audience"
		'pass the global als a param
		test( TScreenHandler_OfficeStatistics.newsColor )
Print "done"
	End Method
End Type
```
I get
```
creating color
creating color
new TStatisticsSubScreen_Audience
done
```

**Comment by GWRon** [comment] 2019-06-15 13:26
Will try this evening...when at home again.

TColor is defined in another file ...and imported (might make the difference?).

**Comment by woollybah** [comment] 2019-06-15 14:13
Well, that's the thing... it's easier to fix a problem with an reproducible example.

**Comment by GWRon** [comment] 2019-06-15 14:27
Sometimes it is pretty difficult to create such an failing example as more complex code structures contain a lot of interfering stuff ;-)

Will try to create such a borked up example when at home and kids in bed.

**Comment by HurryStarfish** [comment] 2019-06-15 14:35
The order of initialization order is ...unstable for some reason.

```BlitzMax
SuperStrict
Framework BRL.StandardIO

Type TTest1
	Global G:Int = Init(1)
	Method New()
		Local x:Int = TTest2.G
	End Method
End Type

Type TTest2
	Global G:Int = Init(2)
End Type

Function Init:Int(i:Int)
	Print "Init(" + i + ")"
	Return i
End Function
```

This code produces 

> Init(1)
> Init(2)

as it should. But add `New TTest1` somewhere in the main block and suddenly the result becomes

> Init(2)
> Init(1)

**Comment by GWRon** [comment] 2019-06-15 15:41
Seems there is at least one dude lurking around here who I can rely on (providing useful failing samples ;-)).

**Comment by woollybah** [comment] 2019-06-18 05:49
The main issue is that the semanting needs to be basically split into 2 passes. Currently, it tries to do everything in one pass, which it has issues with.
The first pass would scan the code for types, functions, args, etc.
The second pass would actually semant the code properly, processing statement blocks and inits, and determining types of things etc.

Or at least, that would be one way to solve some of the issues...

**Comment by GWRon** [comment] 2019-06-18 05:51
Yes this two pass solution is...what I suggested some weeks ago. Imho it is the cleanest solution as it avoids behaviour assumptions.

**Comment by GWRon** [comment] 2019-06-18 05:55
@HurryStarfish  already mentioned the behaviour discrepancies of BlitzMax:

Globals in procedural code ("main" and maybe within functions) are evaluated in order of execution.

Globals in type definitions are initialized before.

So the two-pass-thing should pay attention to what @HurryStarfish described for globals.

**Comment by HurryStarfish** [comment] 2019-06-19 16:57
Yeah, I am currently writing up an issue on those "procedural" `Global`s; initializing those is actually pretty complicated.

@woollybah 
I agree with the two pass solution. My own BlitzMax precompiler did a similar thing: iirc, after parsing it would first do a pass over the AST discover the global, "code order agnostic" elements in the code such as global functions and types (incl. resolving their inheritance relationships) and putting them into the correct scopes (which would be attached to the nodes of the AST).
Then, it would do another pass over the AST nodes (in bottom-up order, starting from the leaves), "semanting" and attaching a type to each of them (which might be null in the case of statements/declarations). With local type inference added, this would potentially turned into multiple passes, as some types could come out as "yet unknown" on the first pass.

This might not be directly related to `Global`s, but one thing that I think really isn't ideal about NG bcc in general is the fact that it does not handle semanting in a way like this: by walking over the AST in a predefined order (top-down/bottom-up) and running a transformation/processing function separately on each node. Instead in bcc, every AST node (*`Expr`, *`Stmt`, ...) itself is responsible for taking care that its children get semanted, and can do so in any way and order it wants. This means that every `Semant` method mixes the two responsibilities of a) doing the actual semantic analysis of the node and b) determining the control flow of the semanting process itself. This imo makes the whole process quite complicated to understand and modify.

**Comment by GWRon** [comment] 2019-12-27 21:16
This is still an issue.

**Comment by GWRon** [comment] 2020-07-16 14:05
@HurryStarfish 
As I did not reach much of you the last weeks and months I want to ask you if you achieved some stuff not included into BCC / NG ?

I still have debug code in my game's code. .. 
```
print "Remove programme color reinitialization when fixed"
``` 

BTW we meanwhile also joined a discord channel - if you prefer to write in a "chat" compared to mail/github issues.
https://discord.gg/udSSJkj

**Comment by GWRon** [comment] 2021-04-21 08:58
This issue should be reopened when not fixed - right?
