### ISSUE TITLE
How do you compare structs? / Add Struct docs 

### ISSUE THREAD

**Issue by DivineDominion** [bmx-ng/bcc#434] opened 2019-04-29 18:05 UTC
Was trying to find out if structs support value type semantics like e.g. in Swift:

```bmx
Struct Foo
    Field x:Int = 123
End Struct

Local a:Foo = New Foo
Local b:Foo = New Foo
If a = b Then Print "Y"
```

## Expected Behavior 

- Getting a boolean result

## Actual Behavior

Compiler error:

```
rror: invalid operands to binary expression ('struct _m_untitled1_Foo' and 'struct _m_untitled1_Foo')
                if(bbt_a==bbt_b){
                   ~~~~~^ ~~~~~
```

## Environment

- Operating System: macOS 10.14
- Output of `bcc -v`: bcc[ng] Release Version 0.99

---

I'd really like to have some documentation on the use of structs in the manual. If I knew where to find out anything about Struct at all, I'd contribute the doc text myself, but I can't :)

**Comment by HurryStarfish** [comment] 2019-04-29 19:15
The way I see it, there are two options for "Expected Behavior" here:
1. Getting compile error, stating that you cannot compare the instances without defining an appropriate `Operator =` for the struct.
2. Getting the result of a member-wise `=` comparison. This would mean every struct type has an implicitly implemented `Operator =`.

Option 1. is easier to implement, and can still be upgraded to 2. later.
Long term, I think 2. is preferrable. It would be nice to implicitly have an `=` operator for every type, since structs are currently the only exception in that regard. You'd still be able to overload it, of course, like you can in class types.

> I'd really like to have some documentation on the use of structs in the manual. If I knew where to find out anything about Struct at all, I'd contribute the doc text myself, but I can't :)

I agree, documentation is lacking.

As a quick explanation:
In BlitzMax-NG, the distinction between classes (defined with the `Type` keyword) and structures (`Struct` keyword) is almost exactly the same as in .NET, so if you know C# or another .NET language, you're good. (.NET documentation on the topic might be useful to read as well.)

Otherwise, I'll try to summarize it here:
- The fundamental main difference between classes and structures (or "structs" for short) is that classes are _reference types_ and structs are _value types_.
Imagine you have a `Type TTest` and a `Struct STest`. `TTest` is a _reference type_, which means any variable `Local x:TTest` stores a reference to an object of it. Multiple variables can store references to the same object. `STest` on the other hand is a _value type_, which means that a variable `Local x:STest` directly stores an instance of it. Any assignment of the instance to another variable creates a copy of it. Just like the built-in primitive types `Int`, `Float`, etc.
```
Type TTest
	Field x:Int
End Type

Local a:TTest = New TTest
a.x = 1
Local b:TTest = a
b.x = 2
' both a.x and b.x are 2 now, because a and b refer to the same object
```
```
Struct STest
	Field i:Int
End Struct

Local x:STest = New STest ' a struct instance is created and assigned to x 
x.i = 1
Local y:STest = x ' a copy of the instance is assigned to y
y.i = 2
' a.x is 1 and b.x is 2 now, because struct variables always hold different instances
```
- Unlike class instances (aka objects), which are created, tracked and destroyed by the garbage collector, struct instances are not. This makes structs faster to create and a good choice for small, simple, immutable types that you might have many instances of - points, vectors, tuples, colors, date/timestamps and similar things.
- On the other hand, this makes structs a poor choice for large types whose instances you don't want to copy all the time. They should also not be used for mutable types: ideally, structs should always be immutable. In other words, all their fields should be marked as `ReadOnly` (unlike `STest` in my example above...) This is to take advantage of the benefits of their copy-on-assignment behaviour, while avoiding bugs/mistakes that might arise from it.
- With structs, there is no "`Null` object reference" like with classes, since variables store the instances directly.
- Structs have several of limitations compared to classes, most notably the fact that they don't support inheritance. They can't extend or be extended by another type. They also cannot implement interfaces (at least for now). And unlike classes, they don't (currently) have any implicitly defined members - such as `ToString`, `Compare`, or, as you noticed, `Operator =`.

**Comment by woollybah** [comment] 2019-05-02 05:47
There's now a check for an appropriate overloaded operator when doing struct comparisons.

**Closed** 2019-05-02 05:46 UTC
