### ISSUE TITLE
bcc-ng self compiling with linux x64 throws "Index out of Bounds"

### ISSUE THREAD

**Issue by Octav14n** [bmx-ng/bcc#87] opened 2015-02-28 11:30 UTC
Steps to reproduce:
0. Start linux
1. Compile bcc-ng to x64 (using x86 bcc-ng)
2. Compile bcc-ng using x64 bcc-ng

It throws the following error:
```Unhandled Exception:Attempt to index array element beyond array length```

I can't debug it at the moment because of this issue with debugging: https://github.com/bmx-ng/brl.mod/issues/11

**Comment by woollybah** [comment] 2015-02-28 18:49
I've found an issue where the debug stack isn't always being handled correctly for an Exit or Continue, which can cause problems in subsequent code.

**Comment by woollybah** [comment] 2015-02-28 21:08
The issue is related to this : 
```blitzmax
If i < args.length And args[i] Then
...
```
Our code here is pre-checking the index before attempting to use the array.
The asm for these two checks are performed independently, in order, along with a range-check on the args[i] expression.

The C generator is producing incorrect code, in that it detects the use of an array index, and generates some code on the preceding line to do a range check. Obviously, in this case that then throws an exception before the If statement is used...

A nice problem for the weekend !  Any ideas? ;-)

**Comment by woollybah** [comment] 2015-02-28 23:57
Should be fixed now.

**Closed by woollybah** 2015-02-28 23:57 UTC
Labels: bug
